### ISSUE TITLE
electron-server crashing

### ISSUE THREAD

**Issue by zam6ak** [bjrmatos/jsreport-electron-pdf#8]
While rendering a large PDF, using "electron-server" strategy jsreport crashed with error.
When I switched to "electron-ipc" or "dedicated-process", the PDF is rendered in about 4 minutes, with 2,498 pages...

I am wanting to use "electron-server" as documentation says that it has most performance....

here is the error when it crashed using "electron-server"
```
2016-11-16T20:53:47.638Z - error: Error when processing render request Error during rendering report: socket hang up Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at X:\Projects\jsreport\node_modules\jsreport-core\lib\render\render.js:144:54
    at _fulfilled (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:756:13)
    at X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:564:44
    at flush (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) requestId=7
2016-11-16T20:53:47.646Z - error: Error during processing request: http://IP_ADDRESS/api/report details: Error during rendering report: socket hang up Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at X:\Projects\jsreport\node_modules\jsreport-core\lib\render\render.js:144:54
    at _fulfilled (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:756:13)
    at X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:564:44
    at flush (X:\Projects\jsreport\node_modules\listener-collection\node_modules\q\q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    
```

**Comment by bjrmatos** [comment]
wow! that is a large document, i haven't tested generating pdf with electron on that scale. 

something i will need to investigate on my free time..

> I am wanting to use "electron-server" as documentation says that it has most performance....

in fact, the most performant strategy is `electron-ipc`, seems like i need to update the docs...

`electron-ipc` was created because we had found some issues with `electron-server` on windows and `electron-ipc` solved all the problems.
